package com.pm.billingservice.grpc;

// These imports are the classes generated by your .proto file and the gRPC library
import billing.BillingResponse;
import billing.BillingServiceGrpc.BillingServiceImplBase;
import io.grpc.stub.StreamObserver;
import net.devh.boot.grpc.server.service.GrpcService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

// @GrpcService tells Spring Boot to start a gRPC server and register this class as a handler
@GrpcService
public class BillingGrpcService extends BillingServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(BillingGrpcService.class);

    /**
     * This method handles the 'CreateBillingAccount' RPC call defined in the proto.
     * @param billingRequest The data sent by the client (patientId, name, email)
     * @param responseObserver A special object used to "push" the response back to the client
     */
    @Override
    public void createBillingAccount(billing.BillingRequest billingRequest, StreamObserver<BillingResponse> responseObserver) {

        log.info("createBillingAccount request received {}", billingRequest);

        // --- Business Logic Area ---
        // This is where you would call a Repository to save to a database:
        // e.g., billingRepository.save(new BillingAccount(billingRequest.getPatientId()));

        // Create the response object using the "Builder" pattern (generated from proto)
        BillingResponse response = BillingResponse.newBuilder()
                .setAccountId("1234") // Hardcoded for now; usually comes from your DB
                .setStatus("Active")
                .build();

        // Sends the response back to the client
        responseObserver.onNext(response);

        // Tells the client: "I'm done sending data, you can close the connection now"
        responseObserver.onCompleted();
    }
}